version: "3.7"
services:
  tomcat:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
#    command: tail -f /dev/null
    ports:
      - '8085:8085'
    volumes:
      - ./tomcat/config/context.xml:/opt/tomcat/conf/context.xml
      - ./tomcat/config/server.xml:/opt/tomcat/conf/server.xml
      - ./tomcat/config/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
      - ./tomcat/config/web.xml:/opt/tomcat/conf/web.xml
      - ./tomcat/config/manager/context.xml:/opt/tomcat/webapps/manager/META-INF/context.xml


#    volumes:
#      - ./:/application
#      - maven-repo:/root/.m2
#  maven:
#    image: maven
#    working_dir: /usr/src/mymaven
#    command: mvn tomcat7:redeploy
##    command: mvn tomcat7:redeploy && tail -f /dev/null
#    links:
#      - tomcat
##    ports:
##      - '8080:8080'
#    volumes:
#      - ./:/usr/src/mymaven
#      - maven-repo:/root/.m2
#      - ./tomcat/config/maven/settings.xml:/usr/share/maven/conf/settings.xml


  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    links:
      - tomcat
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins/config/maven/settings.xml:/usr/share/maven/conf/settings.xml
      - maven-repo:/root/.m2
volumes:
  maven-repo:
