services:
  tomcat:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
    ports:
      - '8085:8085'
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    links:
      - tomcat
    ports:
      - '8080:8080'
    volumes:
      - maven-repo:/root/.m2
volumes:
  maven-repo:
